name: build

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.webapp.outputs.webapp-url }}

    steps:
      - uses: azure/webapps-deploy@v3
        id: webapp
        with:
          app-name: gha-workshop
          publish-profile: ${{ secrets.AZURE_WEBAP_PUBLISH_PROFILE }}
          images: 'ghcr.io/blackmael/codespaces-react:latest'
          restart: true

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set repo name to lowercase!
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - uses: docker/build-push-action@v6
        with:
          tags: ghcr.io/${{ env.REPO_NAME }}
          push: true
          build-args: |
            NPM_TOKEN=${{ secrets.NODE_AUTH_TOKEN }}
            
